---
# tasks file for server
- name: Add the user www-data
  user:
    name: www-data
    shell: /usr/sbin/nologin
    home: /home/www-data
    groups: www-data
    append: yes
  become: yes

- name: Create .ssh folder
  file:
    path: ~www-data/.ssh
    state: directory
    owner: www-data
    group: www-data
    mode: 0700
  become: yes

- name: Upload SSH key
  copy:
    src: ../../key.pem
    dest: ~www-data/.ssh/id_rsa
    owner: www-data
    group: www-data
    mode: 0700
  become: yes

- name: Ensure github.com is a known host
  lineinfile:
    dest: /home/www-data/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
  become: yes
