---
# tasks file for php

- name: Install php extensions
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - php-fpm
    - php-enchant
    - php-mbstring
    - php-mysql
    - php-xml

- name: Setup php-fpm
  replace: dest=/etc/php/7.2/fpm/php.ini regexp="(;cgi.fix_pathinfo=1)" replace="cgi.fix_pathinfo=0"
  notify:
    - restart nginx
  become: yes

- name: Add php settings
  template: src=../../nginx/templates/wp-common.conf dest=/etc/nginx/nginx-wp-common.conf owner=www-data group=www-data mode=0644
  notify:
    - restart nginx
  become: yes
